### ISSUE TITLE
Kafka 1.1

### ISSUE THREAD

**Issue by fbonazza** [amient/affinity#215]
Can't seem to push for some reason, not even to a fork, but we need to build this with Kafka 1.1

They moved an API so there's 2 lines of code to change in EmbeddedKafka (line 80 and 81)
`val broker = BrokerIdZNode.decode(1, tmpZkClient.readData[String]("/brokers/ids/1").getBytes(Charsets.UTF_8)).broker`
`val kafkaBootstrap = broker.brokerEndPoint(ListenerName.forSecurityProtocol(SecurityProtocol.PLAINTEXT)).connectionString()`

following this commit https://github.com/apache/kafka/commit/98296f852f334067553e541d6ecdfa624f0eb689#diff-e7c0042c2c1c5bd511329874559eedcf

**Comment by michal-harish** [comment]
Not sure why you wouldn't be able to push to your fork but I will make a 0.6.7 release where the master will be on Kafka 1.1 and I will move kafka 1.0 into master_kafka_1.0

**Comment by michal-harish** [comment]
Released 0.6.7
